on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    name: OTP ${{ matrix.otp }}

    strategy:
      matrix:
        otp: ["25.3", "23.3"]

    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          rebar3-version: "3.20.0"

      - name: Compile project
        run: rebar3 compile

      - name: Check format
        run: rebar3 fmt --check

      - name: Run tests
        run: rebar3 eunit --verbose
